In [20]:
!pip install nbformat


  Obtaining dependency information for nbformat from https://files.pythonhosted.org/packages/f4/e7/ef30a90b70eba39e675689b9eaaa92530a71d7435ab8f9cae520814e0caf/nbformat-5.9.2-py3-none-any.whl.metadata
  Obtaining dependency information for fastjsonschema from https://files.pythonhosted.org/packages/9d/93/a3ca3cdeb84065d7d8f8df4cb09ab44405f109183c1d2b915ec17574e6b1/fastjsonschema-2.18.0-py3-none-any.whl.metadata
  Obtaining dependency information for jsonschema>=2.6 from https://files.pythonhosted.org/packages/0f/bf/a84bc75f069f4f156e1c0d9892fb7325945106c6ecaad9f29d24360872af/jsonschema-4.19.1-py3-none-any.whl.metadata
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
  Obtaining dependency information for jsonschema-specifications>=2023.03.6 from https://files.pythonhosted.org/packages/1c/24/83349ac2189cc2435e84da3f69ba3c97314d3c0622628e55171c6798ed80/jsonschema_specifications-2023.7.1-py3-none-any.whl.metadata
  Obtaining dependency information for referencing>=0.28.4 from https://

In [21]:
%notebook test_log.ipynb

In [2]:
import numpy as np

In [3]:
x=np.array([[1,2,3],[1,2,3]])
y=np.array([[9,1,2],[2,3,1]])

In [19]:
np.sum((x-y)**2)**0.5

2.8284271247461903

In [26]:
y[0].argsort()

array([1, 2, 0])

In [31]:
lst=[2,2,1,1,3,3,2,1,2]
mode=max(set(lst), key=lst.count)

In [34]:
lst.count

<built-in method count of list object at 0x107072680>


In [35]:
x=[1,2,3,4,5,6,7]
y=[1,2,3,4,5,6,7]

np.array_split(x, 2)

[array([1, 2, 3, 4]), array([5, 6, 7])]

In [36]:
np.array_split(y, 2)

[array([1, 2, 3, 4]), array([5, 6, 7])]

In [5]:
relu=lambda x:np.maximum(0,x)

In [6]:
relu(x)

array([[1, 2, 3],
       [1, 2, 3]])

In [7]:
z=np.array([8,9,7])

In [15]:
l=np.array([-1,2,3,-2])


In [18]:
    d_softmax=sm_probs
    d_softmax[np.arange(X.shape[0]),y]-=1
    #d_ReLu=pass1[pass1>0]
  
    grads['W1']=X.T@(d_softmax@W2.T)
    grads['W2']=pass1.T@d_softmax
    grads['b1']=np.sum(d_softmax@W2.T,axis=1)
    grads['b2']=np.sum(d_softmax,axis=1)

    #Regularization
    grads['W1']+= 2*reg*W1
    grads['W2']+=2*reg*W2

[0 0]


In [22]:
l={1:1,2:2}


In [24]:
for i in l:
    print(i)

1
2


In [25]:
l=[[0.5,0.2,0.3],[0.1,0.7,0.2]]

In [27]:
np.argmax(l,axis=1)

array([0, 1])